- hosts: jinshan_all
       
  pre_tasks:
    - stat: path=/root/.init_done
      register: st

  roles:
    - { role: common, when: ansible_distribution=="CentOS" and ansible_distribution_version|int>=6 and not st.stat.exists}
